# Generated by Django 3.0.2 on 2020-03-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadImage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='hotel_Main_Img',
            new_name='your_image',
        ),
    ]
