# Generated by Django 3.0.2 on 2020-03-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UploadImage', '0002_auto_20200305_1749'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hotel',
            new_name='Images',
        ),
    ]
